on:
  pull_request:
    branches: [master]

jobs:
  comment-test:
    runs-on: ubuntu-latest

    steps:

      - name: get commit message
        run: |
           echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
 
      - uses: actions/checkout@v1
        if: contains( env.commitmsg , '[run bench]' )

      - name: step1
        if: contains( env.commitmsg , '[run bench]' )
        run: echo hello
